### ISSUE TITLE
rotating extruder by any means does not work

### ISSUE THREAD

**Issue by redgoblin88** [oierbravo/create-mechanical-extruder#1]
forge: 43.1.32
create: 0.5.0.f
mechanical extruder: 1.0.1

upon placing the mechanical extruder, you may notice that in some orientations the "andesite shaft" turns and rotates towards your facing however the block itself does not (indicated on the upper level, the shafts indicate the direction that i was facing when i was placing it)

the extruder will only work when powered on one specific side (powered on south side), any other "rotation" of the block it ill not work (as indicated on the lower half where the top left is "pressed down" but the other 3 are not)

using the wrench to rotate the extruder does rotate the "shaft" but it will not rotate the texture
regardless, the rotation is only visual and not functional, so any direction except the direction stated above will not work (as shown in the lower half)

![2022-10-06_12 33 00](https://user-images.githubusercontent.com/13396472/194303322-343dfed3-1b4c-4066-8b15-f322461a77f7.png)

**Comment by oierbravo** [comment]
Wow!
Thanks for your amazing bug report!
I see some issues with the generation of the blockstate.
I'm trying to fix it.

**Comment by oierbravo** [comment]
Done and uploaded!

**Comment by redgoblin88** [comment]
sweet, the update works like a charm! (though has seemingly introduced one bug? i will start this as a new report though as to not confuse people)
