### ISSUE TITLE
Different fluids not working

### ISSUE THREAD

**Issue by benbenlaw** [oierbravo/create-mechanical-extruder#11]
![image](https://user-images.githubusercontent.com/42780877/210786165-ec6f40ae-f836-4736-852d-88ca34709912.png)

there is something wrong with the recipes as the fluids dont seem to matter in any of the custom recipes added 

eg the first recipe requires black lava but if a different colored lava is place it will still produce the first recipe. It seems like a checking issue with the recipe starting

this is in the cryptopolis modpack 

https://www.curseforge.com/minecraft/modpacks/cryptopolis

**Comment by oierbravo** [comment]
Hi!
I'm looking to fix it!

I love and enjoy your modpacks :)

**Comment by benbenlaw** [comment]
haha oh thanks :)

**Comment by oierbravo** [comment]
Hi!

Uploaded fix to curseforge.
I've tested it in the pack, and it seems tom work.

**Comment by benbenlaw** [comment]
awesome thank you so much :)

**Comment by benbenlaw** [comment]
will test and let you know

**Comment by benbenlaw** [comment]
thanks for the fix much appreciated :)
