### ISSUE TITLE
feature request: filter/priority

### ISSUE THREAD

**Issue by redgoblin88** [oierbravo/create-mechanical-extruder#2]
it seems that although new recipes are being created and added, it will prioritise vanilla then "non catalyst" recipes, would it be possible to change this to check for a catalyst first?

or even, possibly a filter on the extruder itself to specify what output you are wanting it to create, in which if the filter and recipe around it match it runs?

as seen here i have added a blue ice recipe to make the cobblestone generator make ice, but its only making cobble. i have also done this with a deepslate block below it to make deepslate renewable but that doesnt work either

![image](https://user-images.githubusercontent.com/13396472/194310703-26add999-8bdd-480c-894e-b72073d740c9.png)

**Comment by oierbravo** [comment]
Hi!
Right now I'm not handling priorities or sorting the recipes and that leads to the kind of lack of controll you mention.
I'll look to put a filter on the block.. I think it's a very Create way. However a sort mechanic or a defined/configurable priority would nice too.

Thanks for your suggestion.

**Comment by oierbravo** [comment]
Both options implemented.
Now the block has a filter for selecting the output.
Added priority for recipes with catalyst.

**Comment by redgoblin88** [comment]
![2022-10-11_12 23 38](https://user-images.githubusercontent.com/13396472/195077553-5232dbb4-018c-4a45-a414-bfd89cfab1ed.png)
just a note that applying the filter does work, however it fails to render what is put in
