### ISSUE TITLE
Create Mechanical Extruder Not Compatible with Create .5.1.a Update

### ISSUE THREAD

**Issue by ClaudiusMinimus** [oierbravo/create-mechanical-extruder#26]
Create Mechanical Extruder version create_mechanical_extruder-1.19.2-1.3.2.i.jar is not compatible with the new Create .5.1.a update.
![image](https://github.com/oierbravo/create-mechanical-extruder/assets/17887664/cb76c58d-91ed-4563-af80-8a605fede4ec)

**Comment by muriplz** [comment]
https://github.com/talrey/CreateDeco/issues/80
https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry/issues/72
https://github.com/PssbleTrngle/SliceAndDice/issues/68

**Comment by oierbravo** [comment]
Done!
