### ISSUE TITLE
Hard Crash when Pondering

### ISSUE THREAD

**Issue by Flapjack24** [oierbravo/create-mechanical-extruder#31]
Hello!

I get this crash when trying to ponder the extruder. This is the only ponder scene that crashes my game; all of the regular Create ponder scenes are fine.

https://bytebin.lucko.me/Joh0DD0got

**Comment by oierbravo** [comment]
Thanks!
I'm looking into it.

**Comment by oierbravo** [comment]
I Think I fixed the issue.
