### ISSUE TITLE
[1.19.2-1.5.3.c-36] Unable to join a server - Cannot write a null registry entry!

### ISSUE THREAD

**Issue by TigerWalts** [oierbravo/create-mechanical-extruder#32]
**Forge**: `1.19.2-43.2.8`, `1.19.2-43.2.23`
**Mod Version**: `1.19.2-1.5.3.c-36`, `1.19.2-1.5.4.c-36`
**Create Version**: `0.5.1.c`
**Other mods**: None

~~https://github.com/oierbravo/createsifter may also be affected as it had similar changes since its last version. I have not yet tested it.~~ - Create Sifting 1.19.2-1.7.5.c-36 is OK

When joining a server the client is disconnected and given the on-screen error:

```
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot write a null registry entry!
```

The previous version `1.19.2-1.5.2.c-36` does not have this problem.

Server Debug log: https://gist.github.com/TigerWalts/94aa5e504868721acccbbdfc025bdae4
Client Debug log: https://gist.github.com/TigerWalts/6573781d6a7e95fd500820d53e45ef8c

The error happens after the loading screen disappears. The game may render for a few frames before the error screen appears.

**Comment by TigerWalts** [comment]
Tested with `1.19.2-1.5.4.c-36` in case it was the same cause. No luck.

**Comment by oierbravo** [comment]
Thanks for the report!
I'm looking into it.

**Comment by oierbravo** [comment]
Thanks too for the logs & all the data! It helps a lot!

**Comment by oierbravo** [comment]
Uploaded a new version with the fix.
