### ISSUE TITLE
Custom recipe doesnt works

### ISSUE THREAD

**Issue by Ocpkayp6662** [oierbravo/create-mechanical-extruder#33]
I added custom recipe but it didnt worked some other mods recipe dosent works either only cobblestone and stone works basalt doesnt works either im playing on 1.19.2

**Comment by oierbravo** [comment]
Thanks for the report.
Can you plz send logs, exact mod & forge versions and the custom recipe code?

**Comment by Ocpkayp6662** [comment]
I use 1.19.2-1.5.4.c-36 version of the mod and Forge 1.19.2-43.2.21
I deleted the log and the recipe but create dreams and desires adds lot of recipe example:
{
  "conditions": [
    {
      "type": "forge:mod_loaded",
      "modid": "create_mechanical_extruder"
    }
  ],
  "type": "create_mechanical_extruder:extruding",
  "ingredients": [

    {
      "fluid": "create:honey",
      "amount": 1000
    },
    {
      "fluid": "minecraft:lava",
      "amount": 1000
    }
  ],
  "result": {
    "item": "create:limestone"
  }
  i also added limestone one my code was also the same one execpt "conditions"
  (sorry if you dont understand anything english is not my first language)

**Comment by oierbravo** [comment]
I'm not hable to reproduce the bug.
The recipe above needs a } a the end. But I suppose that is missing from the copy paste.
Try plz, if you can, with the latest version of the mod and if you can send me the log would be very helpful.
Thanks for your patience

**Comment by Ocpkayp6662** [comment]
I tested the new version and it worked now thank you so much (every recipes works now)

**Comment by oierbravo** [comment]
nice!
