### ISSUE TITLE
extruder accepts rotation from either side

### ISSUE THREAD

**Issue by redgoblin88** [oierbravo/create-mechanical-extruder#4]
it seems that when placing the extruder, it will "face" away from you, which is what i would expect, however if you place it against a shaft then it will be facing "backwards"

but when facing towards or "away" from the rotational input, it will still operate, i assume this is because most of vanilla create kinetic things accepts on both ends so additional work might be needed to allow for only one side to accept

note: using the wrench does work so you can fix it that way, though this is just visual as both ends work as seen below

![2022-10-07_11 28 41](https://user-images.githubusercontent.com/13396472/194533452-f21795b0-c84d-470f-906f-5abceca2bcc8.png)

**Comment by oierbravo** [comment]
Thank!
I'm looking to resolve.
You are correct with the vanilla create asumption... but I think the saw or the drill can give me some direction.

**Comment by oierbravo** [comment]
Create Fans for the win!
I think it's working now. Both placement and one sided shaft.
Connects correctly to the rotation provider.
Added LeftShift key functionality too.
New version uploaded to curseforge.
