### ISSUE TITLE
Add support for multiple outputs and chances

### ISSUE THREAD

**Issue by Danymaddox** [oierbravo/create-mechanical-extruder#46]
It will be very cool if the extruder can generate more than one single item at a time, and even cooler if that output supports .withChance() so modpacks creators can modify even more the recipes that this blocks give.

Thank you!

**Comment by MarioSMB** [comment]
The result does support "count" as I've been using it to crank up the drop rates to 4 - needed to find a way to make people stop creating giant cobblestone generators!
