### ISSUE TITLE
[1.20.1] Apparent bug when entering dedicated servers.

### ISSUE THREAD

**Issue by DankestO** [oierbravo/create-mechanical-extruder#50]
Good afternoon!
I downloaded the latest version of the mod [1.20.1-1.6.0.h-48], and for some reason it wouldn't let me enter the server. It does so without problems when entering a single player world, but not the server.
"Connection lost" appeared when I failed to enter the server.

![image](https://github.com/user-attachments/assets/5129dd61-d85d-4d9c-8d0a-b05b4c3bb356)

I spent a while trying to find out which mod was causing this bug, since I updated several, but it wasn't until I installed the previous version of Create Mechanical Extruder that it started working again.

[debug.log](https://github.com/user-attachments/files/16897056/debug.log)

**Comment by oierbravo** [comment]
Thanks for the report!
Found the issue... working on it.

**Comment by oierbravo** [comment]
I think it's fixed.

**Comment by DankestO** [comment]
Thank you!
