### ISSUE TITLE
Mod breaks with latest version of Create (0.5.0g)

### ISSUE THREAD

**Issue by Nachtflame** [oierbravo/create-mechanical-extruder#9]
Though you list as needing 0.5.0e, it _does_ work on 0.5.0f, but not 0.5.0g
MC 1.19.2

**Comment by genesy** [comment]
@oierbravo please?

**Comment by oierbravo** [comment]
Hi!
Thank for both reports.
I'm having troubles to reproduce the error.

Forge : 43.1.53
Create: 0.5.0.g
Works for me.

Could you please send me an error log and versions you are using? It would help me a lot. 

I just updated the cf page with `G` patch requeriment.

**Comment by genesy** [comment]
nvm new update works thanks!
